Update Aluno.java
Aparece o seguinte erro: 
Error: Could not find or load main class Program.Vetor
Caused by: java.lang.ClassNotFoundException: Program.Vetor